from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def math_it(self):
        screen = self.output_label.text()
        try:
            answer = eval(screen)
            self.output_label.setText(str(answer))
        except:
            self.output_label.setText('Error!')

    def dot_it(self):
        screen = self.output_label.text()
        if '.' in screen:
            pass
        else:
            self.output_label.setText(f'{screen}.')

    def backspace(self):
        if self.output_label.text() == '0':
                self.output_label.setText('0')
        else:
            current_input = self.output_label.text()
            new_input = current_input[:-1]
            if new_input == '':
                self.output_label.setText('0')
            else:
                self.output_label.setText(new_input)

    def press_it(self, pressed):
        if pressed == 'C':
            self.output_label.setText('0')
        else:
            if self.output_label.text() == '0' or self.output_label.text() == 'Error!':
                self.output_label.setText(pressed)
            else:
                self.output_label.setText(f'{self.output_label.text()}{pressed}')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 10, 279, 70))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.output_label.setFont(font)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName("output_label")
        self.output_label.setStyleSheet('background-color: black;color: white;border-radius: 3px;padding: 10px 0;border:2px solid grey;')
        self.percent_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('%'))
        self.percent_button.setGeometry(QtCore.QRect(10, 85, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.percent_button.setFont(font)
        self.percent_button.setObjectName("percent_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('C'))
        self.clear_button.setGeometry(QtCore.QRect(81, 85, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.arrow_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.backspace())
        self.arrow_button.setGeometry(QtCore.QRect(152, 85, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.arrow_button.setFont(font)
        self.arrow_button.setObjectName("arrow_button")
        self.divide_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('/'))
        self.divide_button.setGeometry(QtCore.QRect(223, 85, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divide_button.setFont(font)
        self.divide_button.setObjectName("divide_button")
        self.multiply_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('*'))
        self.multiply_button.setGeometry(QtCore.QRect(223, 156, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiply_button.setFont(font)
        self.multiply_button.setObjectName("multiply_button")
        self.nine_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('9'))
        self.nine_button.setGeometry(QtCore.QRect(152, 156, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nine_button.setFont(font)
        self.nine_button.setObjectName("nine_button")
        self.eight_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('8'))
        self.eight_button.setGeometry(QtCore.QRect(81, 156, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eight_button.setFont(font)
        self.eight_button.setObjectName("eight_button")
        self.seven_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('7'))
        self.seven_button.setGeometry(QtCore.QRect(10, 156, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.seven_button.setFont(font)
        self.seven_button.setObjectName("seven_button")
        self.four_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('4'))
        self.four_button.setGeometry(QtCore.QRect(10, 227, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.four_button.setFont(font)
        self.four_button.setObjectName("four_button")
        self.minus_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('-'))
        self.minus_button.setGeometry(QtCore.QRect(223, 227, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minus_button.setFont(font)
        self.minus_button.setObjectName("minus_button")
        self.six_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('6'))
        self.six_button.setGeometry(QtCore.QRect(152, 227, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_button.setFont(font)
        self.six_button.setObjectName("six_button")
        self.five_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('5'))
        self.five_button.setGeometry(QtCore.QRect(81, 227, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.five_button.setFont(font)
        self.five_button.setObjectName("five_button")
        self.two_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('2'))
        self.two_button.setGeometry(QtCore.QRect(80, 298, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.two_button.setFont(font)
        self.two_button.setObjectName("two_button")
        self.addition_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('+'))
        self.addition_button.setGeometry(QtCore.QRect(222, 298, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.addition_button.setFont(font)
        self.addition_button.setObjectName("addition_button")
        self.three_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('3'))
        self.three_button.setGeometry(QtCore.QRect(152, 298, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.three_button.setFont(font)
        self.three_button.setObjectName("three_button")
        self.one_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('1'))
        self.one_button.setGeometry(QtCore.QRect(9, 298, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.one_button.setFont(font)
        self.one_button.setObjectName("one_button")
        self.plus_minus_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('+/-'))
        self.plus_minus_button.setGeometry(QtCore.QRect(10, 369, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plus_minus_button.setFont(font)
        self.plus_minus_button.setObjectName("plus_minus_button")
        self.zero_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('0'))
        self.zero_button.setGeometry(QtCore.QRect(81, 369, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zero_button.setFont(font)
        self.zero_button.setObjectName("zero_button")
        self.period_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot_it())
        self.period_button.setGeometry(QtCore.QRect(152, 369, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.period_button.setFont(font)
        self.period_button.setObjectName("period_button")
        self.equal_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.math_it())
        self.equal_button.setGeometry(QtCore.QRect(223, 369, 66, 66))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal_button.setFont(font)
        self.equal_button.setObjectName("equal_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.arrow_button.setText(_translate("MainWindow", "<<"))
        self.divide_button.setText(_translate("MainWindow", "/"))
        self.multiply_button.setText(_translate("MainWindow", "x"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.addition_button.setText(_translate("MainWindow", "+"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.plus_minus_button.setText(_translate("MainWindow", "+/-"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.period_button.setText(_translate("MainWindow", "."))
        self.equal_button.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
